# Generated by Django 3.2.9 on 2021-11-17 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feature', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name of catagory')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name of section')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name of product')),
                ('desc', models.TextField(verbose_name='description')),
                ('unit', models.CharField(max_length=25, verbose_name='unit of product')),
                ('status', models.CharField(choices=[('AVL', 'available'), ('UVL', 'unavailable'), ('NOT', 'not set')], max_length=3, verbose_name='status of availiblity of product')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='price of one of product')),
                ('catagory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.catagory', verbose_name='catagory of product')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.seller')),
                ('tags', models.ManyToManyField(blank=True, to='feature.Tag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='catagory',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.section', verbose_name='section of catagories'),
        ),
    ]
