# Generated by Django 3.2.9 on 2021-11-10 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feature', '0002_favorite_product'),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name of user')),
                ('address', models.CharField(max_length=600, verbose_name='address of user')),
                ('email', models.EmailField(max_length=254, verbose_name='email of user')),
                ('gender', models.CharField(choices=[('ML', 'male'), ('FL', 'female'), ('NT', 'notset')], max_length=2)),
                ('phone_number', models.CharField(max_length=14, unique=True, verbose_name='phone_number')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date who user joined')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade.card')),
                ('favorite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feature.favorite')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.card', verbose_name="card's user")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
